### ISSUE TITLE
Js backend: ReferenceError: _idris__123_APPLY0_125_ is not defined

### ISSUE THREAD

**Issue by pkamenarsky** [idris-lang/Idris-dev#3742]
The following code

    module Main

    data Timeout = MkTimeout Ptr

    jscall : (fname : String) -> (ty : Type) ->
              {auto fty : FTy FFI_JS [] ty} -> ty
    jscall fname ty = foreign FFI_JS fname ty

    log : String -> JS_IO ()
    log str = do
      jscall "console.log(%0)" (String -> JS_IO ()) str

    setTimeout : (() -> JS_IO ()) -> (millis : Int) -> JS_IO Timeout
    setTimeout f millis = do
      timeout <- jscall "setTimeout(%0, %1)"
                        (JsFn (() -> JS_IO ()) -> Int -> JS_IO Ptr)
                        (MkJsFn f) millis
      pure $ MkTimeout timeout

    main : JS_IO ()
    main = do
      log "log1"
      timeout <- setTimeout (\_ => log "log2") 500
      pure ()

when compiled with

    idris --codegen node Main.idr -o main.js

prints `log1` but then fails with

    /.../main.js:79
            i$CALL(_idris__123_APPLY0_125_,[oldbase])
                   ^

    ReferenceError: _idris__123_APPLY0_125_ is not defined
        at Timeout._onTimeout (/.../main.js:79:16)
        at ontimeout (timers.js:365:14)
        at tryOnTimeout (timers.js:237:5)
        at Timer.listOnTimeout (timers.js:207:5)

**Comment by jfdm** [comment]
@pkamenarsky Thanks for the issue report, and MFE. 

I personally, don't know much about the JS codegen, however I do know that partial application of foreign function calls can cause undefined behaviour. If you replace jscall with a direct call to the foreign function call, what happens?

**Comment by pkamenarsky** [comment]
@jfdm So i replaced `setTimeout` with:

     setTimeout : (() -> JS_IO ()) -> (millis : Int) -> JS_IO Timeout
    setTimeout f millis = do
      timeout <- foreign FFI_JS "setTimeout(%0, %1)"
                        (JsFn (() -> JS_IO ()) -> Int -> JS_IO Ptr)
                        (MkJsFn f) millis
      pure $ MkTimeout timeout

and made the FFI call directly in `main`:

    main : JS_IO ()
    main = do
      log "loga"
      timeout <- setTimeout (\_ => foreign FFI_JS "console.log(%0)"
                            (String -> JS_IO ()) "log2")
                            500
      pure ()

Unfortunately, this doesn't change anything. The same exception is thrown: `ReferenceError: _idris__123_APPLY0_125_ is not defined`.

**Comment by jfdm** [comment]
Okay, thanks for trying. Quick question, is this related to [IdrisScript](https://github.com/idris-hackers/IdrisScript/)? The code looks familiar....

**Comment by pkamenarsky** [comment]
It's a standalone file without any dependencies, I think I stole jscall
from the online FFI tutorial. I took a look at IdrisScript to see if
they're doing something different though, but it's pretty much the same.

**Comment by edwinb** [comment]
I suspect this is related to a change in name decoration I made just before releasing 1.0, which somehow the JS tests didn't catch. Almost certainly there is a place in the JS backend which needs the old decoration for APPLY replaced with this one. This will be a fairly easy fix if someone feels like digging around for it.

The JS backend gets very little maintenance - it would also be great if someone was able to take this on.

**Comment by pierrebeaucamp** [comment]
I ran into this issue on 1.0.0, but downgrading to 0.99.2 solved the problem for me

**Comment by colbyn** [comment]
Same here...

**Comment by melted** [comment]
This is fixed in the new JS backend.

**Comment by Risto-Stevcev** [comment]
@melted where is the new JS backend?
I tried the same example above with the latest compiler on `idris-dev#master` (13768b9b94c0019315a2806b19ac3a08dd621655) and it's still failing with the same error

**Comment by melted** [comment]
Interesting. I'll check it out!

**Comment by rbarreiro** [comment]
Working fine for me on master
[rbarreiro@rbarreiro-acer idris_tests]$ idris --codegen node t2.idr -o t2.js
[rbarreiro@rbarreiro-acer idris_tests]$ node t2.js 
log1
log2
[rbarreiro@rbarreiro-acer idris_tests]$ cat t2.idr
module Main

data Timeout = MkTimeout Ptr

jscall : (fname : String) -> (ty : Type) ->
          {auto fty : FTy FFI_JS [] ty} -> ty
jscall fname ty = foreign FFI_JS fname ty

log : String -> JS_IO ()
log str = do
  jscall "console.log(%0)" (String -> JS_IO ()) str

setTimeout : (() -> JS_IO ()) -> (millis : Int) -> JS_IO Timeout
setTimeout f millis = do
  timeout <- jscall "setTimeout(%0, %1)"
                    (JsFn (() -> JS_IO ()) -> Int -> JS_IO Ptr)
                    (MkJsFn f) millis
  pure $ MkTimeout timeout

main : JS_IO ()
main = do
  log "log1"
  timeout <- setTimeout (\_ => log "log2") 500
  pure ()

**Comment by Risto-Stevcev** [comment]
@rbarreiro hmm.. it's possible I'm not compiling it correctly or using the right binary
basically I ran `make`, and when it was done I ran ` idris-dev/dist/build/idris/idris --codegen node Blah.idr -o blah.js`
did you do the same sort of thing? which commit did you build and what size was the binary?

**Comment by rbarreiro** [comment]
You are probably using the right idris binary but it is picking up the
wrong backend binary. I don't know how to tell idris where to lookup for
the backend.

Em 06/07/2017 16:57, "Risto Stevcev" <notifications@github.com> escreveu:

**Comment by Melvar** [comment]
You make sure that a directory containing the correct backend binary precedes any containing wrong ones in the `PATH` variable Idris is using.

**Comment by rbarreiro** [comment]
@Risto-Stevcev I usually use the make install command, which replaces all files on the cabal installation folder.

**Comment by Risto-Stevcev** [comment]
@rbarreiro @Melvar thanks for the hints, setting the binary directly in the `PATH` variable worked

```
/path/to/idris-dev/idris-codegen-javascript/idris-codegen-javascript Blah.idc -o blah.js
```
```
PATH=/path/to/idris-dev/dist/build/idris-codegen-javascript:/path/to/idris-dev/dist/build/idris-codegen-node /path/to/idris-dev/dist/build/idris/idris --codegen node Blah.idr -o blah.js
```
