### ISSUE TITLE
Another Totality Checking Problem

### ISSUE THREAD

**Issue by luochen1990** [idris-lang/Idris-dev#4314]
using Idris 1.2.0

# Steps to Reproduce

Load the following code:
```
byteWidth : Type -> Int
byteWidth Nat = 8
```
And then in the REPL:

#Test Case 1:
```
> :doc byteWidth
```

#Test Case 2:
```
> byteWidth Char
```

#Test Case 3:
```
> byteWidth (1=2)
```

# Expected Behavior

#Test Case 1:
```
Main.byteWidth : Type -> Int

    The function is NOT Total
```

#Test Case 2:

Runtime error

#Test Case 3:

Runtime error

# Observed Behavior

#Test Case 1:
```
Main.byteWidth : Type -> Int

    The function is Total
```

#Test Case 2:
```
8 : Int
```

#Test Case 3:
```
8 : Int
```

**Comment by ahmadsalim** [comment]
@luochen1990 Thank you for reporting the issue!
This function is not doing what you think it's doing, `Nat` here is treated as a variable 😄 .

This has been fixed on master.

**Comment by luochen1990** [comment]
I can still reproduce this issue on `master`, following is my idris version info:

```
$ /c/Users/Luo/Github/Idris-dev/.stack-work/dist/5c8418a7/build/Idris/idris.exe --version
1.2.0-git:395e8a07
```

**Comment by LeifW** [comment]
It's not going to let you pattern match on types, but I think it should
warn you of that.
